### ISSUE TITLE
Add Judy's Pflug

### ISSUE THREAD

**Issue by InesSchnelle** [sebokopter/lunchtime#12]
Hi Sebastian,
could you add Judy's Pflug? Address for lunch menu: https://judys-pflug.de/pdf/Mittagstisch.pdf

Also, the Alte Durlacher Brauerei is closed, so you can remove that one.

Thanks!

**Comment by sebokopter** [comment]
Thanks for providing this hint with the infos. I've added it: https://food.heilsen.de/#judys
